import { getContents } from "lib/mdApi";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

type Props = {
  posts: any[];
};

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog-section">
        {!posts.length && <div className="text-2xl text-center pt-9">No posts found.</div>}
        <ul className="list-none">
          {posts.map((frontMatter) => {
            const { slug, date, title, summary } = frontMatter;
            return (
              <li key={slug} className="py-4">
                <article className="space-y-2 xl:grid xl:grid-cols-4 xl:space-y-0 xl:items-baseline">
                  <dl>
                    <dt className="sr-only">Published on</dt>
                    <dd className="text-base font-medium leading-6 text-gray-500 dark:text-gray-400">
                      <time dateTime={date}>
                        {new Date(date).toLocaleDateString("en-US", {
                          year: "numeric",
                          month: "long",
                          day: "numeric",
                        })}
                      </time>
                    </dd>
                  </dl>
                  <div className="space-y-3 xl:col-span-3">
                    <div>
                      <h3 className="text-2xl font-bold leading-8 tracking-tight">
                        <Link href={`/blog/${slug}`}>
                          <a className="text-gray-900 dark:text-gray-100">
                            {title}
                          </a>
                        </Link>
                      </h3>
                      <div className="flex flex-wrap">
                        {/* {tags.map((tag) => (
                        <Tag key={tag} text={tag} />
                      ))} */}
                      </div>
                    </div>
                    <div className="prose text-gray-500 max-w-none dark:text-gray-400">
                      {summary}
                    </div>
                  </div>
                </article>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = getContents();

  return { props: { posts } };
};

export default Home;
