import { GetStaticProps, NextPage } from "next";
import Head from "next/head";

import { Introduction } from "components/Introduction";

type Props = {
  projects: any[];
};

const Home: NextPage<Props> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Introduction />
      {/* <Technologies /> */}
      {/* <Skills /> */}
      {/* <FeaturedMap /> */}
      {/* <ProjectsMap projects={projects} /> */}
      {/* <Contact /> */}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const projects = require("../data/projects.json");

  return {
    props: { projects },
    revalidate: 1,
  };
};

export default Home;
